/* 
	Created by - Akash Patel
	function to generate two arrays and showing matched numbers highlighted.
	showing the result of the lotto.
	
*/
window.onload = function(){
	
	//declaring variables and constatnt here
	const checkedBoxes = document.getElementsByName('number');
	const showTable = document.getElementById('ShowTable');
	const showTable2 = document.getElementById('ShowTable2');
	const elementsManual = document.getElementsByClassName("FirstArray");
	const elementsAuto = document.getElementsByClassName("SecondArray");
	const showResult = document.getElementById("ResultDraw");
	const selectionMethod = document.getElementById("selectionMethod");
	const mainScreenCon = document.getElementById("mainScreenCon");
	const Output = document.getElementById("Output");
	const Input = document.getElementById("Input");
	const errorSel = document.getElementById("errorSel");
	const checkNum = document.getElementsByClassName('activeNum');

	let autoSelected ;
	let matchedNumber ;

	//generating two array and match with each other to generate match numbers and show numbers
	document.getElementById("Playgame").addEventListener("click", function(){
		//generating date,day and time here
		var d = new Date();

		var days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
		
		document.getElementById("currentDate").innerHTML = 'Numbers drawn on '+days[d.getDay()]+', '+d.getFullYear()+' @ '+d.getHours()+':'+d.getMinutes()+':'+d.getSeconds();

		//generating random numbers
		let ranomNumber = Math.floor(Math.random() * 49) + 1; 

		  let checkboxesArray = [];
		
		  //pushing all checked check box values in the array
		  for (var i=0; i<checkedBoxes.length; i++) {
			 if (checkedBoxes[i].checked) {
				checkboxesArray.push(checkedBoxes[i].value);
			 }
		  }

		//check if manual seletcion is selected or auto.
		if(document.getElementById("Manual").checked)
		{
			mainScreenCon.style.display = 'none';
			Input.style.display = 'block'
			tweenCall('Input');
		} 
		else 
		{
			mainScreenCon.style.display = 'none';
			Output.style.display = 'block'
			//generating two autogenerated numbers array here
			//1 autogenerated
			autoSelected = [];
			var autoGenerated = [];
			while(autoSelected.length < 7){
				var r = Math.floor(Math.random()*49) + 1;
				if(autoSelected.indexOf(r) === -1) 
					autoSelected.push(r);
			}

			//2 autogenerated
			while( autoGenerated.length < 7)
			{
				var r = Math.floor(Math.random()*49) + 1;
				if(autoGenerated.indexOf(r) === -1) 
					autoGenerated.push(r);
			}
			//sort autogenerated
			autoSelected = sortArray(autoSelected);

			//generating table of autogenerated array
			let autoResult ='<table  style="font-size: 30px;width: 40%; height:100px;background:black;margin:10px"><tr style="margin:10px">';

			for (var i = 0, len = 6; i < len; i++) {
				autoResult += '<td class="FirstArray" style="padding:35px;width:1%;">'+autoSelected[i]+'</td>';

			}
			autoResult += '</tr></table>';
			showTable.innerHTML = autoResult;
			//sorting array
			autoGenerated = sortArray(autoGenerated);
			
			//generating table of autogenerated array
			let manualResult ='<table  style="font-size: 30px;width: 40%;  height:100px;background:black;margin:10px"><tr style="margin:10px">';

			for (var i = 0, len = 6 ; i < len; i++) {
				manualResult += '<td class="SecondArray" style="padding:35px;width:1%;">'+autoGenerated[i]+'</td>';
			}
			manualResult += '</tr></table>';
			showTable2.innerHTML = manualResult;
			selectionMethod.innerHTML = 'Quick pick selected - your numbers are:';
			
			//getting matched number array here
			matchedNumber = getMatcharray(autoSelected,autoGenerated);
			tweenCall('Output');

		}
		
		// //changing the color of the 1st table
		// for (var i = 0;i < 6; i++) {
		// 	elementsAuto[i].style.background = "#2D2926";
		// }
		
		// //changing the color of the 2nd table
		// for (var i = 0; i < 6 ; i++) {
		// 	elementsManual[i].style.background = "#2D2926";
		// }
		
		 //highlighting matched numbers here
		 for (var i = 0 ; i <= matchedNumber.length-1; i++) 
		 {
			for (var e = 0; e <= 6-1; e++) 
			{
				if(parseInt(elementsAuto[e].innerHTML) ===  parseInt(matchedNumber[i]))
				{
					elementsAuto[e].style.background = "grey";
				}
			}
		} 	

		
		//showing result of draw in the html
		if(matchedNumber.length == 0)
		{
		   showResult.innerHTML = 'Sorry, no numbers matched. Try again next time.'
		} 
		else if(matchedNumber.length == 1)
		{
		   showResult.innerHTML = 'One number matched. Try again next time.'
		}
		else if(matchedNumber.length == 2)
		{
		   showResult.innerHTML = 'Two number matched. Try again next time.'
		}
		else if(matchedNumber.length == 3)
		{
		   showResult.innerHTML = 'You matched 3 numbers. You win enough to by another ticket!'
		}
		else if(matchedNumber.length == 4)
		{
		   showResult.innerHTML = 'You matched 4 number. Drinks are on you!'
		}
		else if(matchedNumber.length == 5)
		{
		   showResult.innerHTML = 'You matched 5 numbers! Time to take that vacation!'
		}
		else
		{
		   showResult.innerHTML = 'You matched all 6 numbers! wow!!! you are rich!!!'
		}
	});

	document.getElementById("playManual").addEventListener("click", function(){

		let ranomNumber = Math.floor(Math.random() * 49) + 1; 

		  let checkboxesArray = [];
		
		  //pushing all checked check box values in the array
		  for (var i=0; i<checkNum.length; i++) {
			    console.log(checkNum[i].innerHTML);
				checkboxesArray.push(checkNum[i].innerHTML);
			 }
		  

		
		 console.log(checkboxesArray);

		//check if total checked check boxes are 6 
		if(checkboxesArray.length<6)
		{
		   errorSel.innerHTML = "Fewer than 6 numbers selected";
		} 
		else if(checkboxesArray.length>6)
		{
		   errorSel.innerHTML = "More than 6 numbers selected";

		} 
		else 
		{
			mainScreenCon.style.display = 'none';
			Output.style.display = 'block';
			Input.style.display = 'none';

			//generating array of autogenerated numbers
			autoSelected = [];
			while(autoSelected.length < 7){
				var r = Math.floor(Math.random()*49) + 1;
				if(autoSelected.indexOf(r) === -1) 
					autoSelected.push(r);
			}
			
			//sorting array
			autoSelected = sortArray(autoSelected);

			//generating table of autogenerated array
			let autoResult ='<table style="font-size: 30px;width: 40%;  height:100px;background:#2D2926; margin:10px"><tr style="margin:10px">';
			for (var i = 0, len = 6; i < len; i++) {
				autoResult += '<td class="FirstArray" style="padding:35px;width:1%;">'+autoSelected[i]+'</td>';
			}
			autoResult += '</tr></table>';

			showTable.innerHTML = autoResult;
			
			//sorting checkbox array
			checkboxesArray = sortArray(checkboxesArray);
			
			//generating table of autogenerated array
			let manualResult ='<table style="font-size: 30px;width: 40%;  height:100px;background:#2D2926; margin:10px"><tr style="margin:10px">';

			for (var i = 0, len = 6; i < len; i++) {
				manualResult += '<td class="SecondArray" style="padding:35px;width:1%;">'+checkboxesArray[i]+'</td>';
			}
			manualResult += '</tr></table>';
			showTable2.innerHTML = manualResult;
			
			selectionMethod.innerHTML = 'You picked the following numbers';

		} 
		//getting matched numbers array
		matchedNumber = getMatcharray(autoSelected,checkboxesArray);

		//changing the color of the 1st table
		// for (var i = 0;i < 6; i++) {
		// 	elementsAuto[i].style.background = "#2D2926";
		// }
		
		//changing the color of the 2nd table
		// for (var i = 0; i < 6 ; i++) {
		// 	elementsManual[i].style.background = "#2D2926";
		// }
		
		 //highlighting matched numbers here
		 for (var i = 0 ; i <= matchedNumber.length-1; i++) 
		 {
			for (var e = 0; e <= 6-1; e++) 
			{
				if(parseInt(elementsAuto[e].innerHTML) ===  parseInt(matchedNumber[i]))
				{
					elementsAuto[e].style.background = "purple";
				}
			}
		} 	

		//showing result of draw in the html
		if(matchedNumber.length == 0)
		{
		   showResult.innerHTML = 'Sorry, no numbers matched. Try again next time.'
		} 
		else if(matchedNumber.length == 1)
		{
		   showResult.innerHTML = 'One number matched. Try again next time.'
		}
		else if(matchedNumber.length == 2)
		{
		   showResult.innerHTML = 'Two number matched. Try again next time.'
		}
		else if(matchedNumber.length == 3)
		{
		   showResult.innerHTML = 'You matched 3 numbers. You win enough to by another ticket!'
		}
		else if(matchedNumber.length == 4)
		{
		   showResult.innerHTML = 'You matched 4 number. Drinks are on you!'
		}
		else if(matchedNumber.length == 5)
		{
		   showResult.innerHTML = 'You matched 5 numbers! Time to take that vacation!'
		}
		else
		{
		   showResult.innerHTML = 'You matched all 6 numbers! wow!!! you are rich!!!'
		}
		tweenCall('Output');
	});

	document.getElementById("Playagaingame").addEventListener("click", function(){
		mainScreenCon.style.display = 'block';
		Output.style.display = 'none';
		Input.style.display = 'none';
		errorSel.innerHTML = '';
		$('.activeNum').removeClass('activeNum');
		
		tweenCall('mainScreenCon');
	});
};

function tweenCall(divId){
	let mainScreenvar = document.getElementById(divId);
	TweenMax.fromTo(mainScreenvar, 1, {
		scale: 0,
		opacity: 0,
		transformOrigin: "center center"
	},{
		scale: 1,
		opacity: 1,
		ease: Power1.easeInOut,
		borderRadius: "10px"
	});

}

function changeClrAct(numThis){
	numThis.classList.toggle("activeNum");
}
//sorting array function
function sortArray(arrayforsort) {
	arrayforsort.sort(function(a, b){
						 return a - b
					 });
	return arrayforsort;
}

//generating matched number array from two array.
function getMatcharray(firstArray, secondArray) {
    var allMatche = [];
    for ( var i = 0; i < firstArray.length - 1; i++ ) {
        for ( var e = 0; e < secondArray.length - 1; e++ ) {
			if ( parseInt(firstArray[i]) === parseInt(secondArray[e]) ) 
			{
				allMatche.push( firstArray[i] );
			}
        }
    }
    return allMatche;
}
