// JavaScript Document
/* 
        
        Name-Akash Kumar Patel
        This program demonstrates how lotto game works, firstly user has two options between selecting their own number from 1-49 or computer will generate for them. WHile on the output screen draws numbers and user number got matched and result is shown.
~*/
//onload function is created
window.onload = function(){
	
	//declaring variables and constants.
	const checkedBoxes = document.getElementsByClassName("Numbers");
	let autoSelected = [];
	const ShowAuto = document.getElementById("ShowAuto");
	const ShowManual = document.getElementById("ShowManual");
	const elementsManual = document.getElementsByClassName("auto");
	const Input = document.getElementById("Input");
	const elementsAuto = document.getElementsByClassName("manual");
	const Result = document.getElementById("Outcome");
	const Selectionradio = document.getElementById("Selectionradio");  
	let matches = [];
	document.getElementById("Input").style.display="none";
	document.getElementById("Output").style.display="none";
	document.getElementById("error1").style.display = "none";
	document.getElementById("error2").style.display = "none";
	 //function which shows the result.
	document.getElementById("PlayLotto").addEventListener("click", function(){

        //generating day,date and time 
		var date = new Date();

		var allDays = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];

		document.getElementById("drawDate").innerHTML = 'Numbers drawn on '+allDays[date.getDay()]+','+ date.getDate() +","+date.getFullYear()+'@ '+date.getHours()+':'+date.getMinutes()+':'+date.getSeconds();

		//checks if random numbers or user numbers has to show on output screen 
		if(document.getElementById("Autopick").checked)
		{
			document.getElementById("mainDiv").style.display="none";
			document.getElementById("Output").style.display="block";
			
            //generating random numbers for both array
			var autoGenerated = [];
			while(autoSelected.length < 7){
				var r = Math.floor(Math.random()*49) + 1;
				if(autoSelected.indexOf(r) === -1) 
					autoSelected.push(r);
			}

			while( autoGenerated.length < 7)
			{
				var r = Math.floor(Math.random()*49) + 1;
				if(autoGenerated.indexOf(r) === -1) 
					autoGenerated.push(r);
			}
			
			autoSelected = myFunction(autoSelected);
			
			//creating table and pass it in to the html
			let autoResult ='<table border=1 style="font-size: 30px;  height:100px; width:500px;">';

			for (var i = 0, len = 6; i < len; i++) {
				autoResult += '<td style="padding:8px;" class="auto" >'+autoSelected[i]+'</td>';
			}
			autoResult += '</tr></table>';
			ShowAuto.innerHTML = autoResult;

			//sorting array
			autoGenerated = myFunction(autoGenerated);

			let manualResult ='<table border=1 style="font-size: 30px;  height:100px; width:500px;">';
		
			for (var i = 0, len = 6 ; i < len; i++) {
				manualResult += '<td class="manual" style="padding:8px;">'+autoGenerated[i]+'</td>';
			}
			manualResult += '</tr></table>';
			ShowManual.innerHTML = manualResult;
			Selectionradio.innerHTML = 'Quick pick selected - your numbers are:';
			matches = getMatch(autoSelected,autoGenerated);
		} else {
			// document.getElementById("PlayLotto").style.marginLeft = "400px";
		  //enter all checkbox values in the array	
		  document.getElementById("error1").style.display = "none";
			document.getElementById("error2").style.display = "none";
        let checkboxesChecked = [];
        for (var i=0; i<checkedBoxes.length; i++) {
            if (checkedBoxes[i].checked) {
				checkboxesChecked.push(checkedBoxes[i].value);
			}
        }

			//check if number of checkbox selected are exact 6
			// document.getElementById("PlayLotto").addEventListener("click", function(){
			document.getElementById("Input").style.display="block";
			// document.getElementById("PlayLotto").style.marginLeft = "100px";
			document.getElementById("mainDiv").style.display="none";
			document.getElementById("error1").style.display = "none";
			document.getElementById("error2").style.display = "none";
			if(checkboxesChecked.length<6)
			{
			document.getElementById("error1").style.display = "block";
			document.getElementById("error1").innerText = "Minimum six numbers required";
			} else if(checkboxesChecked.length>6)
			{
				document.getElementById("error2").style.display = "block";
				document.getElementById("error2").innerText ="Not more than six numbers";

			} else 
			{
				//random numbers in the array
				autoSelected = [];
				while(autoSelected.length < 7){
					var r = Math.floor(Math.random()*49) + 1;
					if(autoSelected.indexOf(r) === -1) 
						autoSelected.push(r);
				}
				//sort array
				autoSelected = myFunction(autoSelected);
				
				//creating table and add it in to the html
				let autoResult ='<table border=1 style="font-size: 30px;  height:100px; width:500px;"><tr >';
				for (var i = 0, len = 6; i < len; i++) {
					autoResult += '<td class="auto" style="padding:10px;">'+autoSelected[i]+'</td>';
				}
				autoResult += '</tr></table>';

				ShowAuto.innerHTML = autoResult;

					
				//sorting array
				checkboxesChecked = myFunction(checkboxesChecked);
				//creating table and pass it in to the html
				let manualResult ='<table border=1 style="font-size: 30px;  height:100px; width:500px;">';
				for (var i = 0, len = 6; i < len; i++) {
					manualResult += '<td class="manual" style="padding:10px;">'+checkboxesChecked[i]+'</td>';
				}
				manualResult += '</tr></table>';
				ShowManual.innerHTML = manualResult;
				Selectionradio.innerHTML = 'You picked the following numbers:';
				document.getElementById("Input").style.display="none";
				document.getElementById("mainDiv").style.display="none";
				document.getElementById("Output").style.display="block";
				document.getElementById("error1").style.display = "none";
				document.getElementById("error2").style.display = "none";

			} 
				// });
			//generating matched number array
			matches = getMatch(autoSelected,checkboxesChecked);

		}

		 //highliting matched numbers
		for (var i = 0 ; i <= matches.length-1; i++) 
		{
			for (var e = 0; e <= 6-1; e++) 
			{
				if(parseInt(elementsAuto[e].innerHTML) ===  parseInt(matches[i]))
				{
					elementsAuto[e].style.background = "purple";
				}
			}
		} 

		
		//showing results bassed on the number of matches
        if(matches.length == 0)
		{
		   Result.innerHTML = 'Sorry, no numbers matched. Try again next time.'
		} 
		else if(matches.length == 1)
		{
		   Result.innerHTML = 'One number matched. Try again next time.'
		}
		else if(matches.length == 2)
		{
		   Result.innerHTML = 'Two number matched. Try again next time.'
		}
		else if(matches.length == 3)
		{
		   Result.innerHTML = 'You matched 3 numbers. You win enough to buy another ticket!'
		}
		else if(matches.length == 4)
		{
		   Result.innerHTML = 'You matched 4 number. Drinks are on you!'
		}
		else if(matches.length == 5)
		{
		   Result.innerHTML = 'You matched 5 numbers! Time to take that vacation!'
		}
		else
		{
		   Result.innerHTML = 'You matched all 6 numbers! wow!!! you are rich!!!'
		}		

	});

//sort array function
function myFunction(arrays) {
	arrays.sort(function(a, b){return a - b});
	return arrays;
}

//generating match number array
function getMatch(a, b) {
    var matches = [];
    for ( var i = 0; i < a.length - 1; i++ ) {
        for ( var e = 0; e < b.length - 1; e++ ) {
			if ( parseInt(a[i]) === parseInt(b[e]) ) 
			{
				matches.push( a[i] );
			}
        }
    }
    return matches;
}
    };